#!/data/data/com.termux/files/usr/bin/sh
## This file is executed during VNC server
## startup.

# Launch terminal emulator Aterm.
# Requires package 'aterm'.
#aterm -geometry 80x24+10+10 -ls &

#xfce4-terminal &

# Launch Tab Window Manager.
# Requires package 'xorg-twm'.
#twm &

openbox-session&


## Fluxbox desktop.

# Generate menu.
#fluxbox-generate_menu

# Start fluxbox.
#fluxbox &

#xfce4-session&

